# set primary Rosé Pine colorscheme colors
set $base           #191724
set $surface        #1f1d2e
set $overlay        #26233a
set $muted          #6e6a86
set $subtle         #908caa
set $text           #e0def4
set $love           #eb6f92
set $gold           #f6c177
set $rose           #ebbcba
set $pine           #31748f
set $foam           #9ccfd8
set $iris           #c4a7e7
set $highlightlow   #21202e
set $highlightmed   #403d52
set $highlighthigh  #524f67

bar {
#    i3bar_command i3bar
    status_command i3status -c ~/.config/i3/bar/i3status.conf
    position top
    output eDP-1
    output HDMI-1-0
    hidden_state hide
    font pango:JetBrains Mono Nerd Font 13
    binding_mode_indicator yes
    padding 2px
    tray_padding 5px
#    tray_output primary
    separator_symbol " | "
    colors{
        background         $base
        statusline         $base
        focused_statusline $text
        focused_separator  $subtext
        focused_workspace  $base $base $rose
        active_workspace   $base $base $rose
        inactive_workspace $base $base $foam
        urgent_workspace   $base $base $love
        binding_mode       $base $base $surface
    }
}
#
# bar {
#     status_command i3blocks -c ~/dotfiles/.config/i3/i3blocks.conf
#         position top
#         output eDP1
#         output HDMI-1-0
#         hidden_state hide
#         font pango:JetBrains Mono Nerd Font 13
#         binding_mode_indicator yes
#         padding 1px
#         tray_padding 5px
#         colors{
#             background         $base
#                 statusline         $base
#                 focused_statusline $text
#                 focused_separator  $blue
#                 focused_workspace  $base $base $flamingo
#                 active_workspace   $base $base $rosewater
#                 inactive_workspace $base $base $sky
#                 urgent_workspace   $base $base $red
#                 binding_mode       $base $base $surface1
#         }
# }
