output * bg ~/Pictures/wally/rj890-wallpaper.cam.jpg fill
exec_always wal -i Pictures/wally/rj890-wallpaper.cam.jpg 
exec_always killall waybar &&  waybar --config ~/.config/waybar/sway-config.jsonc

exec flameshot &
exec nm-applet &
exec blueman-applet &

exec systemctl --user set-environment XDG_CURRENT_DESKTOP=sway
exec systemctl --user import-environment DISPLAY \
                                         SWAYSOCK \
                                         WAYLAND_DISPLAY \
                                         XDG_CURRENT_DESKTOP

exec hash dbus-update-activation-environment 2>/dev/null && \
     dbus-update-activation-environment --systemd DISPLAY \
                                                  SWAYSOCK \
                                                  XDG_CURRENT_DESKTOP=sway \
                                                  WAYLAND_DISPLAY
