set $mod Mod4
# variables

set $term       kitty
set $term-alt   kitty
set $menu       wofi --show drun
set $files      thunar

#bindsym $mod+Return exec $term
floating_modifier $mod normal
bindsym $mod+Return             exec $term
bindsym $mod+Shift+Return       exec $term-alt
bindsym $mod+d                  exec $menu
bindsym $mod+Shift+c            kill
bindsym $mod+q                  reload
bindsym $mod+i                  exec killall waybar && waybar --config ~/.config/waybar/sway-config.jsonc
bindsym $mod+Shift+q exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'

