exec $HOME/.config/scripts/wall.sh
exec_always dunst -c $HOME/dotfiles/.config/dunst/dunstrc -startup_notification
exec --no-startup-id dunst -c $HOME/.config/dunst/dunstrc
exec --no-startup-id nm-applet
exec --no-startup-id blueman-applet &
exec --no-startup-id flameshot &
exec --no-startup-id picom --config $HOME/.config/picom/picom.conf
exec --no-startup-id lxsession --session=i3 --de=i3 & 
exec --no-startup-id nwg-look -a
#exec --no-startup-id sudo powertop --auto-tune
exec_always --no-startup-id xrandr --output eDP-1 --mode 1920x1080 --rate 144.00 --primary
exec --no-startup-id /usr/bin/lxpolkit &
#exec_always --no-startup-id xrandr --output HDMI-1-1 --mode 1920x1080 --refresh 144 --right-of eDP-1 --noprimary
exec_always --no-startup-id xrandr --output HDMI-1-0 --mode 1920x1080 --refresh 119 --right-of eDP-1 --noprimary
exec_always --no-startup-id i3-save-tree --workspace 1 > ~/.i3/workspace-1.json
# exec --no-startup-id xfce4-power-manager
exec --no-startup-id $HOME/.config/polybar/launch.sh
