# Some Security Shit
exec --no-startup-id /usr/bin/lxpolkit &

# Monitor Stuff
exec_always --no-startup-id xrandr --output eDP-1 --mode 1920x1080 --rate 144.00 --primary
exec_always --no-startup-id xrandr --output HDMI-1-0 --mode 1920x1080 --right-of eDP-1 --noprimary --refresh 144

exec --no-startup-id xset r rate 350 25
# wallpaper stuff 
exec --no-startup-id  wal -i /home/jraj/Pictures/wallies/gruvbox_astro.jpg
# exec feh --no-fehbg --bg-fill '/home/jraj/Pictures/wally/forest.jpg'

# Required UI Things
exec --no-startup-id dunst -c $HOME/.config/dunst/dunstrc -startup_notification &
exec --no-startup-id $HOME/.config/i3/scripts/launch_polybar.sh
#exec --no-startup-id lxsession --session=i3 --de=i3 &
exec --no-startup-id nwg-look -a
exec --no-startup-id picom --config $HOME/.config/picom/picom.conf &

# Applications
exec --no-startup-id xinput set-prop "ELAN0788:00 04F3:321A Touchpad" "libinput Tapping Enabled" 1
exec --no-startup-id xinput set-prop "ELAN0788:00 04F3:321A Touchpad" "libinput Natural Scrolling Enabled" 1
#exec --no-startup-id  xinput set-prop 11 "libinput Tapping Enabled" 1 
exec --no-startup-id blueman-applet &
exec --no-startup-id flameshot &
exec --no-startup-id nwg-look -a &
exec --no-startup-id xset s off
exec --no-startup-id xset -dpms
exec --no-startup-id xset s noblank


# power stuff
exec --no-startup-id ~/.config/scripts/battery.sh
# exec --no-startup-id sudo powertop --auto-tune
# exec --no-startup-id xfce4-power-manager
