set $rosewater #f5e0dc
set $flamingo  #f2cdcd
set $pink      #f5c2e7
set $mauve     #cba6f7
set $red       #f38ba8
set $maroon    #eba0ac
set $peach     #fab387
set $yellow    #f9e2af
set $green     #a6e3a1
set $teal      #94e2d5
set $sky       #89dceb
set $sapphire  #74c7ec
set $blue      #89b4fa
set $lavender  #b4befe
set $text      #cdd6f4
set $subtext1  #bac2de
set $subtext0  #a6adc8
set $overlay2  #9399b2
set $overlay1  #7f849c
set $overlay0  #6c7086
set $surface2  #585b70
set $surface1  #45475a
set $surface0  #313244
set $base      #1e1e2e
set $mantle    #181825
set $crust     #11111b

bar {
    i3bar_command i3bar
    status_command i3status -c ~/.config/i3/i3status.conf
    position bottom
    hidden_state hide
    font pango:JetBrains Mono Nerd Font 13
    binding_mode_indicator yes
    padding 2px
    tray_padding 5px
    colors{
        background         $base
        statusline         $base
        focused_statusline $text
        active_workspace   $base $text $blue
        focused_separator  $base
        focused_workspace  $base $base $flamingo
        active_workspace   $base $base $rosewater
        inactive_workspace $base $base $sky
        urgent_workspace   $base $base $red
        binding_mode       $base $base $surface1
    }
}

