# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
separator=true
separator_block_width=15

[weather]
command=curl -Ss 'https://wttr.in/bangalore?format=3' | xargs echo
interval=3600
color=#89dced

[wifi]
command=iw dev | grep ssid | cut -d " " -f 2-
label=Wifi: 
#INTERFACE=wlp0s20f3
interval=30

[memory]
command=free -h |  grep Mem | cut -d " " -f 20
label=Used: 
interval=30


[battery]
command=~/dotfiles/.config/i3/i3blocks/bat
interval=25

[time]
command=date +%T
label=Time: 
interval=10

[update]
command=$HOME/dotfiles/.config/i3/i3blocks/updates
color=#a6e3a1
interval=21600
