set $mod Mod4

gaps inner 10
gaps outer 5

#smart_gaps on
smart_borders on

#default_workspace 1
default_border pixel 2
default_floating_border pixel 3

for_window [class="^.*"] border pixel 2
for_window [class="^.*"] margin-top pixel 1

#default_layout stacking
title_align center
binding_mode_indicator yes
focus_on_window_activation smart
workspace_auto_back_and_forth yes
popup_during_fullscreen all
#force_xinerama yes

# Some workspace config for apps
for_window [class="feh"] floating enable border none
for_window [class="imv"] floating enable border none
for_window [class="Conky"] floating enable border none
for_window [class="Brave-browser" window_role="pop-up"] floating enable, sticky enable, move position 3345 795, resize set 480 270
for_window [class="zen" window_role="PictureInPicture"] floating enable, sticky enable, move position 3345 795, resize set 480 270
#for_window [class="zen" instance="Navigator"] floating enable
for_window [class="Blueman-manager" ] floating enable, move position center
for_window [class="pavucontrol" ] floating enable, move position center

# Send Applications to respective workspace
assign [class="darksoulsremastered.exe" ] 4
assign [class="Lutris"] 3
assign [class="Alacritty"] 1
assign [class="firefox"] 2
assign [class="kitty"] 1
assign [class="Brave"] 2
assign [class="zen"] 2
assign [class="firefox"] 2
assign [class="thorium-browser"] 2
assign [class="chromium"] 2
assign [class="mpv"] 3
assign [class="qBittorrent"] 4
assign [class="discord"] 5
assign [class="obsidian"] 3

# Setting the workspace based of monitors/display
workspace 1 output eDP-1
workspace 2 output HDMI-1-0
workspace 3 output eDP-1
workspace 4 output HDMI-1-0
workspace 5 output eDP-1
workspace 6 output HDMI-1-0
workspace 7 output eDP-1
workspace 8 output HDMI-1-0
workspace 9 output eDP-1

# Title of application is aligned on left when stacked
# title_align left


# Resize config in resize mode
bindsym $mod+r mode "resize"
mode "resize" {
        # Pressing down will grow the window’s height.
        bindsym $left       resize shrink width 10 px or 10 ppt
        bindsym $down       resize grow height 10 px or 10 ppt
        bindsym $up         resize shrink height 10 px or 10 ppt
        bindsym $right      resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left        resize shrink width 10 px or 10 ppt
        bindsym Down        resize grow height 10 px or 10 ppt
        bindsym Up          resize shrink height 10 px or 10 ppt
        bindsym Right       resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}
