#!/usr/bin/env bash
set -euo pipefail

if ! command -v swayidle &> /dev/null; then
    notify-send "Swayidle is missing"
    exit 1
fi

case "${1:-}" in
    kill)
        systemctl  --user disable --now swayidle.service
        notify-send "Swayidle: Disabled" "please make sure to check logs incase any issues"
        ;;
    start)
        systemctl --user add-wants niri.service swayidle.service
        systemctl --user start swayidle.service
        notify-send "Swayidle: Enabled" "please make sure to check logs incase any issues"
        ;;
    *)
        notify-send "Usage: $(basename "$0") <start|kill>" >&2
        exit 1
        ;;
esac
