unbind r
bind r source ~/.tmux.conf

set -g prefix C-s
set-option -sg escape-time 7
set-option -g focus-events on
set-option -sa terminal-features ',$TERM:RGB'
#vim keybindings
setw -g mode-keys vi
setw -g mouse on

bind-key h select-pane -L
bind-key l select-pane -R
bind-key j select-pane -D
bind-key k select-pane -U

set -g repeat-time 500

bind-key -r -T prefix       C-k       resize-pane -U
bind-key -r -T prefix       C-j       resize-pane -D
bind-key -r -T prefix       C-h       resize-pane -L
bind-key -r -T prefix       C-l       resize-pane -R
bind-key C-l send-keys 'C-l'


run '~/.tmux/plugins/tpm/tpm'
