unbind r
bind r source ~/.tmux.conf

set -g prefix C-s
set-option -sg escape-time 7
set-option -g focus-events on
set-option -sa terminal-features ',$TERM:RGB'
#vim keybindings
setw -g mode-keys vi
setw -g mouse on

bind-key h select-pane -L
bind-key l select-pane -R
bind-key j select-pane -D
bind-key k select-pane -U

set -g repeat-time 500

bind-key -r -T prefix       C-k       resize-pane -U
bind-key -r -T prefix       C-j       resize-pane -D
bind-key -r -T prefix       C-h       resize-pane -L
bind-key -r -T prefix       C-l       resize-pane -R
bind-key C-l send-keys 'C-l'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-battery'
set -ag terminal-overrides ",$TERM:RGB"
set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_status_enable "yes"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_fill "none"

set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_status_modules_right "application session user host date_time battery"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M:%S"

run '~/.tmux/plugins/tpm/tpm'
