### MY KEYBINDS

# Setting SUPER to be Mainmod
$mainMod = SUPER

# Some EveryDay Programs
$terminal       = kitty
$fileManager    = thunar
$browser        = zen-browser
$browser_alt    = firefox
$menu           = wofi --show drun
$relaod         = hyprctl reload


# Custom Binds
bind = $mainMod,        Return,         exec,           $terminal
bind = $mainMod,        E,              exec,           $fileManager
bind = $mainMod,        D,              exec,           $menu
bind = $mainMod,        B,              exec,           $browser
bind = $mainMod,        R,              exec,           $reload
bind = $mainMod SHIFT,  B,              exec,           $browser_alt
bind = $mainMod SHIFT,  V,              exec,           pavucontrol
bind = $mainMod,        V,              exec,           ~/.config/scripts/volumeswitch
bind = $mainMod,        X,              exec,           hyprlock --config ~/.config/hypr/hyprlock.conf
bind = $mainMod,        I,              exec,           killall waybar && notify-send "Killed waybar"
bind = $mainMod SHIFT,  I,              exec,           waybar & disown && notify-send "Started waybar"

# Hyprland related binds
bind = $mainMod SHIFT,  C,              killactive,
bind = $mainMod SHIFT,  Q,              exit,
bind = $mainMod SHIFT,  S,              togglesplit, 
bind = $mainMod,        Space,          togglefloating,
bind = $mainMod,        F,              fullscreen,
bind = $mainMod,        S,              pseudo,
bind = $mainMod,        Tab,            cyclenext,
bind = $mainMod,        Tab,            bringactivetotop,

# Lid switch to lock the window manager
bindl = , switch:on:[Lid Switch], exec, hyprlock --config ~/.config/hypr/hyprlock.conf
bindl = , switch:on:[Lid Switch], exec, hyprctl keyword monitor "eDP-1, disable"
bindl = , switch:on:[Lid Switch], exec, hyprctl keyword monitor "HDMI-A-1, disable"
bindl = , switch:off:[Lid Switch], exec, hyprctl keyword monitor "eDP-1, 1920x1080@144.0, 0x0, 1"
bindl = , switch:off:[Lid Switch], exec, hyprctl keyword monitor "HDMI-A-1, 1920x1080@119.98, 1920x0, 1"

source = ~/.config/hypr/hyprland/keybind/workspace.conf
source = ~/.config/hypr/hyprland/keybind/window.conf
source = ~/.config/hypr/hyprland/keybind/multimedia.conf
