# Move focus with mainMod + arrow keys
# bind = $mainMod, left, movefocus, l
# bind = $mainMod, right, movefocus, r
# bind = $mainMod, up, movefocus, u
# bind = $mainMod, down, movefocus, d

#window/workspace related binds
bind = $mainMod, h, movefocus,  l
bind = $mainMod, l, movefocus,  r
bind = $mainMod, k, movefocus,  u
bind = $mainMod, j, movefocus,  d

# swallow-like binds`
bind = $mainMod, M, fullscreenstate, 1
bind = $mainMod SHIFT, M, fullscreenstate, 2
bind = $mainMod, Comma, fullscreenstate, 0


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

