$font = Iosevka Nerd Font
$font_bold = Iosevka Nerd Font Mono Bold

general {
    hide_cursor = false
    ignore_empty_input = true
}


animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/Pictures/wally/malenia-edit.jpg
    blur_passes = 0
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 5
    inner_color = rgba(111, 73, 52, 0.9) # no fill

    outer_color =  rgba(195,94,41,0.8)
    check_color = rgba(196,195,193,0.8)
    fail_color = rgba(195, 94, 41, 0.8)

    font_color = rgb(196,195,193)
    fade_on_empty = false
    rounding = 10

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    position = 30, 260
    halign = left
    valign = bottom
}

# TIME
label {
    monitor =
    text = $TIME 
    font_size = 96
    font_family = $font_bold
    position = 30, -120
    halign = left
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A / %B %d"
    font_size = 25
    font_family = $font

    position = 30,-260
    halign = left
    valign = top
}

# USer
label{
   monitor = 
   text = $USER
   font_size = 48
   font_family = $font_bold
   position = 30, -660
   halign = left
   valign = top
}

