[Service]
ExecStart=
ExecStart=/usr/bin/swayidle -w timeout 300 'swaylock -f -i /home/jraj/Pictures/wally/malenia-edit.jpg' timeout 360 'niri msg action power-off-monitors' resume 'niri msg action power-on-monitors' before-sleep 'pgrep swaylock || swaylock -f -i /home/jraj/Pictures/wally/malenia-edit.jpg'
