[Service]
ExecStart=
ExecStart=/usr/bin/swayidle -w timeout 300 'swaylock -i /home/jraj/Pictures/wally/wall_4.jpeg' timeout 360 'niri msg action power-off-monitors' resume 'niri msg action power-on-monitors' before-sleep 'pgrep swaylock || swaylock -i /home/jraj/Pictures/wally/wall_4.jpeg'
