# ENVIRONMENT VARIABLES
env = XCURSOR_SIZE,24
env = HYPRLAND_TRACE=1
env = GTK_THEME,rose-pine
#env = HYPRCURSOR_SIZE,10
env = XCURSOR_THEME, Bibata-Moderen-Ice
env = HYPRCURSOR_THEME, Bibata-Moderen-Ice

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
    disable_splash_rendering = true
    font_family = "JetBrainsMono Nerd Font"
#    vrr = 3
    enable_swallow = true
}
xwayland{
    enabled = true
}

# imports
source = ~/.config/hypr/decor.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/hypr/devices.conf
source = ~/.config/hypr/auto.conf
