source = ~/.config/hypr/hyprland/hw.conf
source = ~/.config/hypr/hyprland/autostart.conf
source = ~/.config/hypr/hyprland/window.conf
source = ~/.config/hypr/hyprland/feel.conf
source = ~/.config/hypr/hyprland/keybind/global.conf
#source = ~/.cache/wal/colors-hyprland.conf


# ENVIRONMENT VARIABLES
ecosystem:no_update_news=true

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,sway
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia


# PERMISSIONS

# ecosystem {
#   enforce_permissions = 1
# }
#
# permission = /usr/(bin|local/bin)/flameshot, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/hyprlock, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/hyprlock, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

