windowrulev2 = nomaximizerequest, class:.* # You'll probably like this.
windowrulev2= opacity 0.9,class:(pavucontrol)$
windowrulev2= float, class:^(pavucontrol)$
windowrulev2= size 600 700, class:^(pavucontrol)$
windowrulev2= stayfocused, class:^(pavucontrol)$
windowrulev2= workspace 1, class:^(kitty)$

