# volume menu
windowrulev2= opacity 0.9,class:(org.pulseaudio.pavucontrol)$
windowrulev2= float, class:^(org.pulseaudio.pavucontrol)$
windowrulev2= size 800 700, class:^(org.pulseaudio.pavucontrol)$
windowrulev2= stayfocused, class:^(org.pulseaudio.pavucontrol)$

# kitty only in workspace 1
windowrulev2= workspace 1, class:^(kitty)$
windowrulev2= bordersize 1, class:^(kitty)$
windowrulev2= bordercolor rgb(11ccff), class:^(kitty)$

windowrulev2 = stayfocused, class:^(pinentry-)
windowrulev2 = workspace 5, class:^(.*)(lutris)$

windowrulev2= workspace 4, class:^(org.qbittorrent.qBittorrent)$

windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = size 700 350, title:^(Picture-in-Picture)$
windowrulev2 = move 62% 65%, title:^(Picture-in-Picture)$

windowrulev2 = float, title:^(nwg-look)$
windowrulev2 = size 1000 800, title:^(nwg-look)$

windowrulev2 = workspace 4, class:^(obsidian)$
# windowrulev2= float, class:^(org.qbittorrent.qBittorrent)$, title:!(qBittorrent v4.6.5)
