# WINDOWS AND WORKSPACES

windowrule = float,class:^(zen)$,title:^(Picture-in-Picture)$
windowrule = float,class:^(zen)$,title:^(Parent process Browser Console)$
windowrule = move 1450 750,class:^(zen)$,title:^(Picture-in-Picture)$
windowrule = size 450 300,class:^(zen)$,title:^(Picture-in-Picture)$
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = workspace 2,class:^(zen)$
windowrule = workspace 3,class:^(obsidian)$
windowrule = workspace 1,class:^(kitty)$
windowrule = float,class:^(org.pulseaudio.pavucontrol)$
windowrule = float,class:^(blueman-manager)$
windowrule = center,class:^(blueman-manager)$
windowrule = size 400 700,class:^(blueman-manager)$


# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]
workspace = 1, monitor:eDP-1,default:true
workspace = 2, monitor:HDMI-A-1,default:true
workspace = 3, monitor:eDP-1,default:true
workspace = 4, monitor:HDMI-A-1,default:true
# workspace = 2, rounding:false, bordersize:0
# workspace = 2, gapsout:0, gapsin:10

dwindle {
    pseudotile = true
    preserve_split = true 
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = false
}
