backend = "glx";

opacity-rule = [
     "73:class_g = 'kitty' && focused",
     "73:class_g = 'kitty' && !focused",
     "50:class_g = 'dunst' && focused",
     "50:class_g = 'dunst' && !focused",
     # "96:class_g = 'zen' && focused",
     # "80:class_g = 'zen' && !focused",
     "83:class_g = 'Rofi' && focused",
     "83:class_g = 'Rofi' && !focused",

    ];

blur-background = "true"
blur-method = "dual_kawase";
blur-strength = 4;

fading = true;
fade-delta = 7;


corner-radius = 5

rounded-corners-exclude = [
  "window_type = 'dock'"
];

shadow = true
shadow-radius = 15;
shadow-opacity = 1

shadow-exclude = [
    "class_g ?= 'polybar'"
]

vsync = true;
blur-background-fixed = true;
