backend = "glx";

opacity-rule = [
     "50:class_g = 'dunst' && focused",
     "50:class_g = 'dunst' && !focused",
     # "96:class_g = 'zen' && focused",
     # "80:class_g = 'zen' && !focused",
     "87:class_g = 'Rofi' && focused",
     "87:class_g = 'Rofi' && !focused",

    ];


rounded-corners-exclude = [
  "window_type = 'dock'",
  "class_g ?= 'dmenu'",
  "class_g ?= 'dwm'"
];

blur-background         = "true"
blur-method             = "dual_kawase";
blur-strength           = 4;

fading                  = true;
fade-delta              = 7;


corner-radius           = 10;

shadow                  = true;
shadow-radius           = 5;
shadow-opacity          = 1;
shadow-offset-x         = 0;
shadow-offset-y         = 0;
crop-shadow-to-monitor  = true;
shadow-opacity          = 0.35;
shadow-radius           = 12;

shadow-exclude = [
    "class_g ?= 'polybar'",
    "class_g ?= 'dock'",
]

animations = ({
    triggers = ["close", "hide"];
    preset = "slide-out";
    direction = "up";
    },
    {
    triggers = ["open", "show"];
    preset = "slide-in";
    direction = "down";
})

vsync                 = true;
blur-background-fixed = true;
shadow-ignore-shaped  = true;

wintypes : {
    tooltip = {
        fade = true;
        shadow = true;
        opacity: 0.75;
        focus: true;
    },
    dock = { shadow=false; }
    popup_menu = {
        shadow=true;
        fade=true;
        clip-shadow-above=true;
        full-shadow=false;
        blur-background=false;
    }
    dropdown_menu = {
        shadow=false;
        opacity:0.5;
    }
}
