# Recommended location for database

# If running mpd using systemd, delete this line to log directly to systemd.
log_file           "syslog"

# The music directory is by default the XDG directory, uncomment to amend and choose a different directory
music_directory    "/home/jraj/Music"
playlist_directory    "/home/jraj/Music/Playlists"

# Uncomment to refresh the database whenever files in the music_directory are changed
auto_update "yes"
bind_to_address "127.0.0.1"
restore_paused "yes"
max_output_buffer_size "16384"

audio_output {
    type "pulse"
    name "pulse"
}

audio_output {
    type "fifo"
    name "Visualizer feed"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}
