import=["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
normal={family="JetBrains Mono Nerd Font", style="medium"}
size=12.0

[window]
opacity=0.85
dynamic_padding = true
blur=true

[scrolling]
history=100000

[selection]
save_to_clipboard=true

[cursor]
style={ shape="Beam",blinking="Always"}
