
[font]
normal={family="JetBrains Mono Nerd Font", style="medium"}
size=13.0

[window]
opacity=0.97
dynamic_padding = true

[scrolling]
history=100000

[selection]
save_to_clipboard=true

[cursor]
style={ shape="Beam",blinking="Always"}

[general]
import=["~/.config/alacritty/catppuccin-mocha.toml"]
