; Polybar configuration
;

[colors]
background        = ${xrdb:background:#1e1e1e}
foreground        = ${xrdb:foreground:#fefefe}
primary           = ${xrdb:color2:#efefef}
secondary         = ${xrdb:color3:#efefef}
secondary-alt     = ${xrdb:color4:#efefef}
alert             = ${xrdb:color5:#ee0000}
disabled          = ${xrdb:color1:#1c1c1c}

[bar/main]
width                   = 100%
height                  = 20pt
radius                  = 0
background              = ${colors.background}
foreground              = ${colors.foreground}
border-size             = 0pt
padding-left            = 1
padding-right           = 1
border-color            = ${colors.background}
border-top              = 10
border-bottom           = 10
module-margin           = 0
separator               = |
separator-foreground    = ${colors.background}
font-0                  = "JetBrainsMono Nerd Font:size=11;2"
modules-left            = i3 xwindow
modules-center          = wifi date 
modules-right           = pulseaudio battery temperature time systray
cursor-click            = pointer
cursor-scroll           = ns-resize
monitor                 = eDP-1
enable-ipc              = false

[bar/sec]
width                   = 100%
height                  = 20pt
radius                  = 0
background              = ${colors.background}
foreground              = ${colors.foreground}
border-color            = ${colors.background}
border-size             = 0pt
padding-left            = 1
padding-right           = 1
border-top              = 10
border-bottom           = 10
module-margin           = 0
separator               = |
separator-foreground    = ${colors.background}
font-0                  = "JetBrainsMono Nerd Font:size=11;2"
modules-left            = i3 xwindow
modules-center          = wifi  
modules-right           = pulseaudio battery temperature time systray
cursor-click            = pointer
cursor-scroll           = ns-resize
monitor                 = HDMI-1-0
enable-ipc              = false

include-file = ~/.config/polybar/modules.ini

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
