;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;
;==========================================================

include-file = $HOME/.config/polybar/mocha.ini

[bar/mybar]
width = 100%
height = 24pt
# radius = 0
background = #881e1e2e
foreground = ${colors.text}
# offset-x = 00 
# offset-y = 0
; line-size = pt
# border-size = 0pt
# border-color = ${colors.mantle}
padding-left = 1
padding-right = 1
module-margin = 1
separator = |
separator-foreground = ${colors.pink}
font-0 = Fira Code Nerd Font:style=Medium:size=10;0
font-1 = Font Awesome 6 Free:style=solid;0
modules-left = i3 
modules-center = xwindow checkupdates
modules-right = backlight battery xkeyboard memory cpu wlan date systray
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
scroll-up="#i3.prev"
scroll-down="#i3.next"

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3

# override-redirect = true

[module/systray]
type = internal/tray
format-margin = 5pt
tray-spacing = 5pt

[module/i3]
type = internal/i3
show-urgent = true
index-sort = true
enable-click = true
enable-scroll = true
reverse-scroll = false
label-focused = %index%
label-focused-foreground = ${colors.rosewater}
label-focused-underline = ${colors.text}
# label-focused-background = ${colors.text}
label-focused-padding = 1
label-unfocused-padding = 1


[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/checkupdates]
type=custom/script
exec=checkupdates | wc -l
format= Update: <label>

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted =  %percentage_used%%
label-unmounted =   
label-mounted-foreground = ${colors.teal}
label-unmounted-foreground = ${colors.read}

[module/alsa]
type = internal/alsa
master-soundcard = default
label-muted = 🔇 muted
label-muted-foreground = #66
ramp-volume-0 = 🔈
ramp-volume-1 = 🔉
ramp-volume-2 = 🔊
ramp-headphones-0 = 🎧
ramp-headphones-1 = 🎧
; click-right =
; click-middle =

[module/pulseaudio]
type = internal/pulseaudio
; sink = alsa_output.pci-0000_12_00.3.analog-stereo
use-ui-max = true
interval = 5
reverse-scroll = false

[module/xkeyboard]
type = internal/xkeyboard
format=<label-indicator>
format-foreground=${colors.red}
label-indicator-padding = 0
label-indicator-margin = 0
# label-indicator-foreground = ${colors.text}
indicator-icon-0 = caps lock;-CL;+CL
indicator-icon-1 = scroll lock;;+SL
indicator-icon-2 = num lock;-NL;+NL1

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.yellow}
label = %percentage_used:2%%
label-foreground= ${colors.yellow}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.sky}
label-foreground= ${colors.sky}
label = %percentage:2%%


[module/wlan]
type = internal/network
interface=wlp0s20f3
label-connected =   %essid% 
label-disconnected =    
label-connected-foreground=${colors.green}
label-disconnected-foreground=${colors.red}

[module/battery]
type = internal/battery
full-at = 99
low-at = 25
battery = BAT0
adapter = ADP1
poll-interval = 5
format-discharging=<ramp-capacity> <label-discharging>
format-discharging-foreground=${colors.peach}
format-charging = <animation-charging> <label-charging>
format-charging-foreground=${colors.green}
ramp-capacity-0 =  
ramp-capacity-1 =  
ramp-capacity-2 =    
ramp-capacity-3 =  
ramp-capacity-4 =  
bar-capacity-width = 100
animation-charging-0 =   
animation-charging-1 =   
animation-charging-2 =   
animation-charging-3 =   
animation-charging-4 =   
; Framerate in milliseconds
animation-charging-framerate = 750


[module/eth]
type = internal/network
interface = eno1
label-connected =   %ifname%
label-disconnected =   
label-connected-foreground=${colors.green}
label-disconnected-foreground=${colors.red}

[module/date]
type = internal/date
interval = 1
date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/backlight]
type = internal/backlight
card = acpi_video0
use-actual-brightness = true
poll-interval = 0
enable-scroll = true
scroll-interval = 10
format =   <label>
label = %percentage%%
bar-width = 10
bar-indicator = |
bar-fill = ─
bar-empty = ─
